# Generated by Django 5.0 on 2023-12-08 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AddField(
            model_name='produto',
            name='criado',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 12, 8, 18, 48, 34, 566370, tzinfo=datetime.timezone.utc), verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='modificado',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 12, 8, 18, 49, 3, 797688, tzinfo=datetime.timezone.utc), verbose_name='Data de Atualização'),
            preserve_default=False,
        ),
    ]
